### ISSUE TITLE
Q about building `patchelf-pypi`

### ISSUE THREAD

**Issue by kloczek** [mayeut/patchelf-pypi#119]
Currently `patchelf-pypi` buld procedure seems is using git submodules with patchelf which builds patchelf binary.

If that is correct is it possible to build `patchelf-pypi using system installed patchelf binary? 🤔

**Comment by mayeut** [comment]
No, it's not possible. It's meant to build a specific version from sources.
Why do you ask ?

**Comment by kloczek** [comment]
Because so far I didn't found any reason why it cannot be system installed patchelf binary ..

**Comment by mayeut** [comment]
This distribution is to install with pip/pipx, if you want to install the system one, please use your system package manager.

**Comment by kloczek** [comment]
Issue is that it is not possible to build your module which will ne using system install patchelf binary.

**Comment by kloczek** [comment]
> Please expand thoroughly on the use-case rather than the feature you wish was available and won't be.

I'm packaging your module into rpm package.
I have no wishes. I'm only asking (please one more time look on the issue title).

**Comment by mayeut** [comment]
> is it possible to build `patchelf-pypi using system installed patchelf binary?

No it's not and it won't be.

The PyPI packaging is only meant to ease installation using pip/pipx but shall not be an "always required" dependency of any other package (kind of like the cmake or ninja PyPI distibution from [scikit-build org](https://github.com/scikit-build)).

**Comment by kloczek** [comment]
> The PyPI packaging is only meant to ease installation using pip/pipx but shall not be an "always required" dependency of any other package (kind of like the cmake or ninja PyPI distibution from [scikit-build org](https://github.com/scikit-build)).

So this package soes not make any sense. Instead require those pip/pipx better is just check availability f the ninja and patchelf executables 🤔
