### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by parekcze** [mayeut/patchelf-pypi#72]
Hello,

after upgrade **patchelf** to version **0.17.2.0** I have problem with make static binary of python scripts with **staticx**.

Failing command: `staticx binary binary.static`

With version "0.17.0.0" it works correctly, but with version "0.17.2.0" I have this error:
`Assertion failed: splitIndex != -1 (patchelf.cc: shiftFile: 504)`
`staticx: patchelf returned -6`

OS: Debian 11
Python: 3.9.2
staticx : 0.13.8

**Comment by aricwang88** [comment]
Same problem when build docker image of python, it cause QEMU crash: 
#18 2.870 DEBUG:root:Running ['patchelf', '--no-default-lib', '/tmp/staticx-prog-u693vhmx']
#18 3.220 Assertion failed: splitIndex != -1 (patchelf.cc: shiftFile: 504)
#18 3.220 qemu: uncaught target signal 6 (Aborted) - core dumped

**Comment by mayeut** [comment]
Thanks for the reports however this repo only aims at providing a rebuild of patchelf on PyPI to ease installation of patchelf for Python users.
Most likely, the issues you're seeing would be reproduced using the binaries or a rebuild of upstream and thus would need to be reported upstream: https://github.com/NixOS/patchelf

I'll update the README to make this clearer.
